### ISSUE TITLE
reverse swaps: remember time of payment

### ISSUE THREAD

**Issue by jackstar12** [BoltzExchange/boltz-client#125]

**Comment by kilrau** [comment]
You mean writing it into the db when invoice was successfully paid?

**Comment by kilrau** [comment]
You mean writing it into the db when invoice was successfully paid? @jackstar12

**Comment by jackstar12** [comment]
> You mean writing it into the db when invoice was successfully paid? @jackstar12

Yes. Would be useful for integrations like BTCPay
