### ISSUE TITLE
submarine swaps: allow specifying max fee

### ISSUE THREAD

**Issue by jackstar12** [BoltzExchange/boltz-client#127]

**Comment by kilrau** [comment]
Can you explain what you had in mind? Autoswap has a budget and manual swaps show fees already.

**Comment by jackstar12** [comment]
A client being able to set a maximum fee they are willing to pay. 
But I think it would make more sense to have an `EstimateFee` rpc which will return a fee estimate for a reverse / submarine / chain swap given an amount.
