### ISSUE TITLE
rpc: custom fee and block targets when paying swaps from internal wallets

### ISSUE THREAD

**Issue by jackstar12** [BoltzExchange/boltz-client#134]

**Comment by kilrau** [comment]
For https://github.com/BoltzExchange/boltz-client/issues/108

**Comment by michael1011** [comment]
I am not a fan of block targets and very much prefer setting fee rates

**Comment by jackstar12** [comment]
> I am not a fan of block targets and very much prefer setting fee rates

wanna do something similar to mempool (low / high / medium prio) and a custom option?

**Comment by kilrau** [comment]
Then 1:1 mempool  (low / high / medium prio) that states sats/vbyte each and also customs sats/vbyte

**Comment by jackstar12** [comment]
note that other fee providers like electrum use a block based approach. but those can internally use certain block amount fors low / high / medium.

**Comment by michael1011** [comment]
I'd just leave it for now. Block based approaches are.... not so great especially in fee spikes. And low / medium / high prios you'd need to explain what that even means in our context
