### ISSUE TITLE
Add `--any-amount` for `createchainswap`

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-client#140]
Originally mentioned [here](https://github.com/BoltzExchange/boltz-client/pull/136#pullrequestreview-2019657049), but not supported by backend yet. Please push for backend support as part of this issue, won't open anything on backend side.

**Comment by kilrau** [comment]
> won't open anything on backend side.

Well I did: https://github.com/BoltzExchange/boltz-backend/issues/579

**Comment by michael1011** [comment]
This is now possible because https://github.com/BoltzExchange/boltz-backend/pull/659 is merged
