### ISSUE TITLE
Unexpected End of File error while executing channel creation swaps 

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-client#21]
```
INFO : 2020/08/26 17:23:03 [BTC] Swap yY1w3y status update: channel.created
INFO : 2020/08/26 17:23:03 [BTC] Status of Swap yY1w3y is channel.created already
ERROR: 2020/08/26 17:24:03 [BTC] Could not listen to events of Swap yY1w3y: Get "https://boltz.exchange/api/streamswapstatus?id=yY1w3y": unexpected EOF
INFO : 2020/08/26 17:24:03 [BTC] Retrying to listen to events of Swap yY1w3y in 15 seconds
INFO : 2020/08/26 17:24:18 [BTC] Reconnected to event stream of SwapyY1w3y
INFO : 2020/08/26 17:24:18 [BTC] Swap yY1w3y status update: channel.created
INFO : 2020/08/26 17:24:18 [BTC] Status of Swap yY1w3y is channel.created already
ERROR: 2020/08/26 17:25:18 [BTC] Could not listen to events of Swap yY1w3y: Get "https://boltz.exchange/api/streamswapstatus?id=yY1w3y": unexpected EOF
INFO : 2020/08/26 17:25:18 [BTC] Retrying to listen to events of Swap yY1w3y in 15 seconds
```

Possibly caused due to miscommunication with OpenSSL libs. Setting the secure protocol explicitly might solve it.

**Comment by frzguida** [comment]
It's solved? i have same issue on the latset boltz-lnd version.

**Comment by michael1011** [comment]
@frzguida are you seeing the exact same error? On testnet or mainnet? Could you send me your logs here?

**Comment by frzguida** [comment]
@michael1011 Here is my log. 
I think the channel was created, but the streamswapstatus api error is the same. 
invoice is set and no chage status.
I'm on a windows machine. and mainnet.
@peartobear What does mean "Setting the secure protocol explicitly might solve it" ? Where can i set it ? 
[boltz.log](https://github.com/BoltzExchange/boltz-lnd/files/6205969/boltz.log)

**Comment by michael1011** [comment]
@frzguida Hm. This looks really weird. Are you running the daemon behind some VPN or Tor instance? Let me try to reproduce this.

We have a reconnection logic, so these errors you see should only be an inconvenience and not break the Swap flow.

> What does mean "Setting the secure protocol explicitly might solve it" ? Where can i set it ?

This is not relevant anymore. We had an issue where a SSL certificate expired and caused connection issues. That problem is fixed.

**Comment by frzguida** [comment]
Well, i have both, TOR and VPN, but bolt daemon does not know about Tor. and even if i run without VPN the error back again.
how can i help you ?

**Comment by kilrau** [comment]
Not relevant anymore, as we discontinued channel creation swaps.
