### ISSUE TITLE
SSL connection to CLN fails using a custom certificate

### ISSUE THREAD

**Issue by s373nZ** [BoltzExchange/boltz-client#218]
After following the instructions in the CLN documentation [here](https://docs.corelightning.org/docs/grpc#generating-custom-certificates-optional) to install a custom certificate into CLN (in order to run CLN under SSL over Tor), the `boltzd` service is failing to connect to CLN with the error:

```
2024-07-20 15:31:08.930 [WARN ] Could not connect to lightning node: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match cln"
```

The `ServerName` for certificate validation is hardcoded [here](https://github.com/BoltzExchange/boltz-client/blob/c4d290c746e536c9100bcb31a488b444a9e03138/cln/cln.go#L79). One option is to regenerate my custom certificates with `cln` included as a SAN, but it sounds like `boltzd` shouldn't make such particular assumptions regarding the certificate settings, especially with custom certificates supported by CLN.

**Comment by kilrau** [comment]
Yep, we'll fix this on our end

**Comment by kilrau** [comment]
Fix is on master as you can see, we plan to include this in an official release towards end of the week

**Comment by kilrau** [comment]
Release with the fix is finally out, sorry for the wait: https://github.com/BoltzExchange/boltz-client/releases/tag/v2.1.1
